FROM azul/zulu-openjdk-alpine
RUN apk update

ENV ACTIVEMQ_VERSION 5.15.10
ENV ACTIVEMQ apache-activemq-$ACTIVEMQ_VERSION
ENV TARFILE $ACTIVEMQ-bin.tar.gz
ENV ACTACCOUNT act1appl
ENV ACTACCOUNT_HOME /home/act1appl

ENV ACTIVEMQ_HOME /opt/$ACTIVEMQ
ENV ACTIVEMQ_SCRIPT activemq.sh
COPY $TARFILE /tmp
RUN tar xfz /tmp/$TARFILE -C /opt 
RUN adduser  -D -s /bin/bash $ACTACCOUNT
COPY $ACTIVEMQ_SCRIPT /
RUN chown $ACTACCOUNT /$ACTIVEMQ_SCRIPT
RUN chmod +x /$ACTIVEMQ_SCRIPT

RUN chown -R $ACTACCOUNT /opt/$ACTIVEMQ
WORKDIR $ACTIVEMQ_HOME
EXPOSE 61616 8161 5672

USER $ACTACCOUNT

CMD [ "/activemq.sh" ]


