FROM azul/zulu-openjdk-alpine
RUN apk update

ENV ACTIVEMQ_VERSION 5.15.10
ENV ACTIVEMQ apache-activemq-$ACTIVEMQ_VERSION

ENV ACTACCOUNT act1appl
ENV ACTACCOUNT_HOME /home/act1appl

ENV ACTIVEMQ_HOME /opt/$ACTIVEMQ
ENV ACTIVEMQ_SCRIPT activemq.sh

RUN adduser  -D -s /bin/bash $ACTACCOUNT
RUN mkdir -p $ACTACCOUNT_HOME/bin/
COPY $ACTIVEMQ_SCRIPT /
RUN chown -R $ACTACCOUNT $ACTACCOUNT_HOME
RUN chgrp -R $ACTACCOUNT $ACTACCOUNT_HOME
RUN chown $ACTACCOUNT /$ACTIVEMQ_SCRIPT
RUN chmod +x /$ACTIVEMQ_SCRIPT

COPY $ACTIVEMQ-bin.tar.gz /tmp/$ACTIVEMQ-bin.tar.gz

RUN tar xf /tmp/$ACTIVEMQ-bin.tar.gz -C /opt/ 
RUN chown -R $ACTACCOUNT $ACTIVEMQ_HOME
RUN chgrp -R $ACTACCOUNT $ACTIVEMQ_HOME
RUN rm /tmp/$ACTIVEMQ-bin.tar.gz

WORKDIR $ACTIVEMQ_HOME
EXPOSE 61616 8161 5672

USER $ACTACCOUNT

CMD [ "/activemq.sh" ]


